---
language: python
python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - git clone https://github.com/geerlingguy/ansible-role-java.git /home/travis/build/fubarhouse/ansible-role-youtrack/tests/roles/geerlingguy.java
  - cd tests
  - ansible-playbook ./test.yml -i inventory --syntax-check
  - ansible-playbook -i inventory ./test.yml --sudo -vvvv
  - sudo service youtrack status
  - sudo service youtrack version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/