---

- name: "Include detection tasks"
  include: tasks-youtrack-detect.yml

#- name: "Include clean-up tasks"
#  include: tasks-youtrack-clean.yml
#  when: 'youtrack_status is defined and "{{ youtrack_installed_version.stdout }}" != "{{ youtrack_version }}"'

- name: "Include youtrack distribution tasks"
  include: tasks-youtrack-distribution.yml
  when:
    - init_file.stat.exists|bool == false
    - youtrack_version_stripped.stdout not in youtrack_installed_version.stdout

- name: "Include config tasks"
  include: tasks-config.yml
  when:
    - init_file.stat.exists|bool == false
    - youtrack_version_stripped.stdout not in youtrack_installed_version.stdout

- name: "Include youtrack service tasks"
  include: tasks-youtrack-service.yml
  when:
    - init_file.stat.exists|bool == false
    - youtrack_version_stripped.stdout not in youtrack_installed_version.stdout

- name: "YouTrack | Apache vhost tasks"
  shell: "echo 'notify apache handler'"
  notify: vhosts-apache
  when: fubarhouse_webserver is defined and fubarhouse_webserver == 'apache2'

- name: "YouTrack | NGINX vhost tasks"
  shell: "echo 'notify nginx handler'"
  notify: vhosts-nginx
  when: fubarhouse_webserver is defined and fubarhouse_webserver == 'nginx'