---

- name: "Include setup tasks"
  include: tasks-initial.yml

- name: "Include webserver installation tasks"
  include: tasks-webserver-install.yml

- name: "Include detection tasks"
  include: tasks-youtrack-detect.yml

#- name: "Include clean-up tasks"
#  include: tasks-youtrack-clean.yml

- name: "Include config tasks"
  include: tasks-config.yml

- name: "Include youtrack distribution tasks"
  include: tasks-youtrack-distribution.yml

- name: "Include vhosts apache2 tasks"
  include: tasks-vhosts-apache2.yml
  when: apache2_is_installed is defined

- name: "Include vhosts nginx tasks"
  include: tasks-vhosts-nginx.yml
  when: nginx_is_installed is defined

- name: "Include webserver restart tasks"
  include: tasks-webserver-restart.yml