---

- name: "YouTrack | Looking for initialisation script"
  stat:
    path: /etc/init.d/youtrack
  register: init_file

- name: "YouTrack | Detect installation"
  shell:  sudo /etc/init.d/youtrack status
  register: youtrack_status
  failed_when: false

- name: "YouTrack | Get version"
  shell:  sudo /etc/init.d/youtrack version
  register: youtrack_installed_version
  failed_when: false