---

- name: "YouTrack | Get distribution"
  get_url:
    url: "http://download.jetbrains.com/charisma/youtrack-{{ youtrack_version }}.{{ youtrack_build }}.zip"
    dest: "/tmp/youtrack-{{ youtrack_version }}.{{ youtrack_build }}.zip"
    validate_certs: no
  tags:
  - youtrack

- name: "YouTrack | Ensure directory is writable"
  file:
    path: "{{ youtrack_install_dir }}"
    state: directory
    mode: 0755
    recurse: true
  tags:
  - youtrack

- name: "YouTrack | Unpack distribution"
  unarchive:
    src: "/tmp/youtrack-{{ youtrack_version }}.{{ youtrack_build }}.zip"
    dest: "{{ youtrack_install_dir }}"
    copy: "no"
  tags:
  - youtrack

- name: "YouTrack | Locate configuration file"
  stat:
    path: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version }}.{{ youtrack_build }}/conf/internal/bundle.properties"
  register: youtrack_config

- name: "YouTrack | Configure for use"
  shell: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version }}.{{ youtrack_build }}/bin/youtrack.sh configure --listen-port {{ youtrack_port }} --base-url {{ youtrack_domain }}"
  register: youtrack_config