---

- name: "Config | Copy initialization script"
  template:
    src: ../templates/debian.j2
    dest: /etc/init.d/youtrack
    owner: root
    group: root
    mode: 0755

- name: "Config | Install intialization script"
  shell: update-rc.d youtrack defaults