---

- name: "YouTrack | Service | Stop"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: stopped

- name: "YouTrack | Service | Start"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: started

- name: "YouTrack | Setup port in configuration"
  become: yes
  become_user: root
  replace:
    dest: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version_stripped.stdout }}/conf/internal/bundle.properties"
    regexp: "8080"
    replace: "{{ youtrack_port }}"
  tags:
  - youtrack
  when: not youtrack_config.stat.exists

- name: "YouTrack | Service | Stop (config changed)"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: stopped
  when: not youtrack_config.stat.exists

- name: "YouTrack | Service | Start (config changed)"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: started
  when: not youtrack_config.stat.exists