---

- name: "YouTrack | Stop service"
  shell: '/etc/init.d/youtrack stop'
  failed_when: false

- name: "YouTrack | Removing init.d script"
  file:
    path: "/etc/init.d/youtrack"
    state: absent

- name: "YouTrack | Remove file system"
  file:
    path: "{{ youtrack_install_dir }}"
    state: absent