---

- name: "YouTrack | Get distribution"
  become: yes
  become_user: root
  get_url:
    url: "http://download.jetbrains.com/charisma/youtrack-{{ youtrack_version }}.zip"
    dest: "/tmp/youtrack-{{ youtrack_version }}.zip"
    validate_certs: no
  tags:
  - youtrack

- name: "YouTrack | Ensure directory is writable"
  become: yes
  become_user: root
  file:
    path: "{{ youtrack_install_dir }}"
    state: directory
    mode: 0755
    recurse: true
  tags:
  - youtrack

- name: "YouTrack | Unpack distribution"
  become: yes
  become_user: root
  unarchive:
    src: "/tmp/youtrack-{{ youtrack_version }}.zip"
    dest: "{{ youtrack_install_dir }}"
    copy: "no"
  tags:
  - youtrack

- name: "YouTrack | Locate configuration file"
  stat:
    path: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version }}/conf/internal/bundle.properties"
  register: youtrack_config
  failed_when: false