---

- name: "YouTrack | Detect installation"
  stat:
    path: /etc/init.d/youtrack
  register: init_file
  changed_when: false
  failed_when: false

- name: "YouTrack | Get version"
  shell:  /etc/init.d/youtrack version
  register: youtrack_installed_version
  changed_when: false
  failed_when: false