---

- name: "YouTrack | Service | Stop"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: stopped

- name: "YouTrack | Service | Start"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: started

- name: "YouTrack | Re-locate configuration file"
  stat:
    path: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version_stripped.stdout }}/conf/internal/bundle.properties"
  register: youtrack_config_recheck
  failed_when: false
  when: not youtrack_config.stat.exists

- name: "YouTrack | Setup port in configuration"
  become: yes
  become_user: root
  replace:
    dest: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version_stripped.stdout }}/conf/internal/bundle.properties"
    regexp: "8080"
    replace: "{{ youtrack_port }}"
  tags:
  - youtrack
  when: youtrack_config_recheck is defined and youtrack_config_recheck.stat.exists

- name: "YouTrack | Service | Stop (config changed)"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: stopped
  when: youtrack_config_recheck is defined and youtrack_config_recheck.stat.exists

- name: "YouTrack | Service | Start (config changed)"
  become: yes
  become_user: root
  service:
    name: youtrack
    state: started
  when: youtrack_config_recheck is defined and youtrack_config_recheck.stat.exists