---

- name: "YouTrack | Download and extract distribution"
  unarchive:
    src: "http://download.jetbrains.com/charisma/youtrack-{{ youtrack_version }}.{{ youtrack_build }}.zip"
    dest: "/usr/local"
    remote_src: yes
    validate_certs: no

- name: "YouTrack | Renaming destination folder"
  shell: "mv /usr/local/youtrack-{{ youtrack_version }}.{{ youtrack_build }} {{ youtrack_install_dir }}"

- name: "YouTrack | Locate configuration file"
  stat:
    path: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version }}.{{ youtrack_build }}/conf/internal/bundle.properties"
  register: youtrack_config

- name: "YouTrack | Configure for use"
  shell: "{{ youtrack_install_dir }}/youtrack-{{ youtrack_version }}.{{ youtrack_build }}/bin/youtrack.sh configure --listen-port {{ youtrack_port }} --base-url {{ youtrack_domain }}"
  register: youtrack_config