---

- name: "Config | Create user group"
  become: yes
  become_user: root
  group:
    name: youtrack
    state: present

- name: "Config | Add users"
  become: yes
  become_user: root
  user:
    name: youtrack
    shell: /bin/false
    state: present
    group: youtrack

- name: "Config | Create directories"
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: directory
    owner: youtrack
    group: youtrack
    mode: 0777
    recurse: true
  with_items:
    - "{{ youtrack_install_dir }}"

- name: "Config | Copy initialization script"
  become: yes
  become_user: root
  template:
    src: ../templates/initialization/script.sh
    dest: /etc/init.d/youtrack
    owner: root
    group: root
    mode: 0755

- name: "Config | Install intialization script"
  become: yes
  become_user: root
  shell: /usr/sbin/update-rc.d youtrack defaults

- name: "Config | Copy runner script"
  become: yes
  become_user: root
  template:
    src: ../templates/run/script.sh
    dest: "{{ youtrack_install_dir }}/youtrack.sh"
    owner: root
    group: root
    mode: 0755