---
# handlers file for fubarhouse.youtrack

- name: "Restart YouTrack"
  shell: /etc/init.d/youtrack restart

- name: "Start YouTrack"
  shell: /etc/init.d/youtrack start

- name: "Stop YouTrack"
  shell: /etc/init.d/youtrack stop
